version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: unless-stopped

    env_file:
      - .env
    environment:
      - API__INSTANCE_APP_NAME=template-api
      - POSTGRES__HOST=postgres
      - POSTGRES__PORT=5432
    depends_on:
      - postgres
      - migrations
      - redis
    ports:
      - ${API__PORT}:5000

    command: [
      "poetry", "run", "uvicorn", "app:create_app",
      "--host", "0.0.0.0",
      "--port", '5000',
    ]

  postgres:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile

    restart: unless-stopped

    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_DATABASES="test_${POSTGRES__DATABASE_NAME}","${POSTGRES__DATABASE_NAME}"
    ports:
      - ${POSTGRES__PORT}:5432
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data/pgdata

  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES__HOST=postgres
      - POSTGRES__PORT=5432
    depends_on:
      - postgres
    command: [
        "bash", "./scripts/wait-for-server.sh", "postgres:5432", "-t", "120",
        "--",
        "poetry", "run", "python", "-m", "scripts.migrate"
    ]

  grafana:
    build:
      context: .
      dockerfile: docker/grafana/Dockerfile
    env_file:
      - .env
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - prometheus

    volumes:
      - ${GRAFANA_VOLUME}:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/

  prometheus:
    image: prom/prometheus:latest

    user: root
    env_file:
      - .env
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./src/prometheus:/prometheus
    depends_on:
      - centrifugo
      - api
    command:
      - --config.file=/etc/prometheus/prometheus.yml

networks:
  default:
    driver: bridge
