{
 "title": "API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Python 3.8.6",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg\" alt=\"\" style='height: 100%; width: 100%; object-fit: contain'>"
   }
  },
  {
   "title": "Requests in progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_in_progress{path_template!~\"/metrics\", path_template!~\"/openapi.json|/docs|/\", method!~\"OPTIONS\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(starlette_requests_processing_time_seconds_count{path_template!~\"/metrics\", path_template!~\"/openapi.json|/docs|/\", method!~\"OPTIONS\"}[$__rate_interval])",
     "legendFormat": "{{method}}: {{path_template}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "rate(starlette_responses_total{path_template!~\"/metrics\", path_template!~\"/openapi.json|/docs|/\", method!~\"OPTIONS\", status_code=~\"4..|5..\"}[$__rate_interval])",
     "legendFormat": "{{status_code}}: {{path_template}}"
    }
   ]
  }
 ]
}