scrape_configs:
- job_name: centrifugo
  scrape_interval: 5s
  static_configs:
  - targets:
    - centrifugo:8000
- job_name: api
  scrape_interval: 5s
  static_configs:
  - targets:
    - api:5000
- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9100