# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: env
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false

        if [ -f pyproject.toml ]; then poetry install --only main; fi
    - name: Start procesing Linters for code quality
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry install --with linters
        
        flake8 ${files_to_check}
        docformatter -cr ${files_to_check}
        black --check ${files_to_check}
        mypy ${files_to_check}
    - name: Start procesing Sasts for code quality
      run: |
        poetry install --with sasts
        
        bandit -r $files_to_check -x tests
        safety check --full-report
    - name: Test with pytest
      run: |
        poetry install --with tests
        pytest tests
